name: TEST AND DEPLOY
on:
#  pull_request:
#     types:
#       - closed
#     branches:
#       - main
#  workflow_dispatch:
   push:
    branches:
      [ main ]
   
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Assign or Get Tag
      id: get-tag
      uses: delta-bravo277/github-action-tag.git@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        
    - name: Print GIT tag
      id: determine-tag
      env:
        NEW_TAG: ${{ steps.get-tag.outputs.tag }}
        PART: ${{ steps.get-tag.outputs.part }}
      run: |
        echo $NEW_TAG
        echo $PART

    - name: Deployment Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      with:
          html_file: 'index.html'

    - name: Get URL
      env: 
          URL: ${{ steps.html_preview.outputs.url }}
      run: |
          echo $URL
